// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqvBvObFQYm4orxEbP3c918I1AzzSnJNU',
    appId: '1:1025044685415:web:50c626a37dd048ad0daac2',
    messagingSenderId: '1025044685415',
    projectId: 'howdy-be002',
    authDomain: 'howdy-be002.firebaseapp.com',
    storageBucket: 'howdy-be002.appspot.com',
    measurementId: 'G-5TXWCDW9YJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8Cpiv6TRutWefRu6p21UhOE8uaJVVZdw',
    appId: '1:1025044685415:android:cad21ca10256a21c0daac2',
    messagingSenderId: '1025044685415',
    projectId: 'howdy-be002',
    storageBucket: 'howdy-be002.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkrG-vHbKpzF3MeJNoaquiS7d89cRyNZA',
    appId: '1:1025044685415:ios:7771a123fb3a3ebc0daac2',
    messagingSenderId: '1025044685415',
    projectId: 'howdy-be002',
    storageBucket: 'howdy-be002.appspot.com',
    iosBundleId: 'com.example.howdy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAkrG-vHbKpzF3MeJNoaquiS7d89cRyNZA',
    appId: '1:1025044685415:ios:a79782dee9417a9c0daac2',
    messagingSenderId: '1025044685415',
    projectId: 'howdy-be002',
    storageBucket: 'howdy-be002.appspot.com',
    iosBundleId: 'com.example.howdy.RunnerTests',
  );
}
